# Generated by Django 5.0.7 on 2024-07-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_created_at_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('delivered', 'Delivered')], max_length=50),
        ),
    ]
